'use strict';

const asyncHandler = require('../utils/asyncHandler');
const { config, describeConfig } = require('../config/env');
const db = require('../config/db');
const { aiService } = require('../services/aiService');
const { knowledgeService } = require('../services/knowledgeService');
const { DISCLAIMER_OBJECT } = require('../utils/disclaimer');

/**
 * GET /api/health — liveness + dependency status.
 *
 * Deliberately reports *whether* the AI is configured without revealing
 * anything about the key, and never returns database credentials.
 */
const health = asyncHandler(async (req, res) => {
  const database = await db.healthCheck();
  const schema = database.status === 'up' ? await db.assertSchema().catch(() => null) : null;

  const healthy = database.status === 'up' && (!schema || schema.ok);

  res.status(healthy ? 200 : 503).json({
    success: healthy,
    data: {
      status: healthy ? 'ok' : 'degraded',
      service: 'loan-information-assistant-api',
      version: require('../../package.json').version,
      projectCode: '4SU24CS045',
      environment: config.env,
      uptimeSeconds: Math.floor(process.uptime()),
      timestamp: new Date().toISOString(),
      database: {
        status: database.status,
        latencyMs: database.latencyMs,
        name: config.database.database,
        schemaReady: schema ? schema.ok : null,
        missingTables: schema ? schema.missing : null,
      },
      ai: {
        configured: aiService.isConfigured(),
        model: aiService.getModel(),
        mode: aiService.isConfigured() ? 'openai' : 'offline_knowledge',
        note: aiService.isConfigured()
          ? 'Answers are generated by the configured model and grounded with the local knowledge base.'
          : 'OPENAI_API_KEY is not set. The assistant is answering from the local knowledge base, which keeps every other feature working.',
      },
      knowledge: {
        groundingEnabled: true,
        keywordCount: knowledgeService.STOP_WORDS ? 'available' : 'unavailable',
      },
      config: describeConfig(),
      disclaimer: DISCLAIMER_OBJECT,
    },
  });
});

/** GET /api/health/live — cheap liveness probe for process managers. */
const live = asyncHandler(async (req, res) => {
  res.json({ success: true, data: { status: 'alive', timestamp: new Date().toISOString() } });
});

module.exports = { health, live };
